# -*- coding: utf-8 -*-
"""Batch B Day 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9s69xMg1-ZNu1JwsXIb6ZLDyQPkAsMd
"""

arr=[2,4,2,5,7,8,3,7,2,1,6]
arr[6]=7
print(arr)
d={
    2:1,
    5:4,
    7:3
}
d[5]=2
print(d)

# fequency counting
arr=[2,4,3,5,7,8,3,7,2,1,6]
freq = {}
for i in arr:
    freq[i] = freq.get(i,0) + 1
print('Frequency of elements in the array:')
print(freq)

# find the first non repeating element
arr=[2,4,3,5,7,8,3,7,2,1,6]
freq={}
for i in arr:
    freq[i] = freq.get(i,0) + 1
for i in arr:
    if freq[i] == 1:
        print(i)
        break

# find the first repeating element
arr=[2,4,3,5,7,8,3,7,2,1,6]
freq={}
for i in arr:
    freq[i] = freq.get(i,0) + 1
for i in arr:
    if freq[i] > 1:
        print(i)
        break

# return the duplicates elements in list
arr=[2,4,3,5,7,8,3,7,2,1,6]
freq={}
for i in arr:
    freq[i] = freq.get(i,0) + 1
dup=[]
for i in arr:
    if freq[i] > 1:
        dup.append(i)
print(dup)

# return the duplicates elements in set
arr = [2, 4, 3, 5, 7, 8, 3, 7, 2, 1, 6]
seen = set()
dup = set()
for i in arr:
    if i in seen:
        dup.add(i)
    else:
        seen.add(i)
print(dup)

x=(2,3)
print(type(x))

# names.for example if the input is rohith sharama the output be rs.

name=input("Enter your name:").split()
print(name[0][0].upper()+name[1][0].upper()+".")

res = input("Enter match results: ")
max_streak=current_streak=0
for i in res:
    if i == 'W':
        current_streak =current_streak + 1
        max_streak = max(max_streak, current_streak)
    else:
      current_streak=0
print(max_streak)

