# -*- coding: utf-8 -*-
"""Batch2 day 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyR4qX-pz1hLvtOt1IJ_ZibdzMuLYqKn

#                                           Day4
"""

for i in "nriit":
  print(i)

"""1. find how many vowels, consonants, spaces and special characters"""

x="python is a programmming language."
vowels="aeiouAeiou"
vowel_count=consonant_count=space_count=special_char_count=0
for char in x:
  if char.isalpha():
    if char in vowels:
      vowel_count+=1
    else:
      consonant_count+=1
  elif char.isspace():
    space_count+=1
  else:
    special_char_count+=1
print(f"Vowels:{vowel_count}")
print(f"Consonants:{consonant_count}")
print(f"Spaces:{space_count}")
print(f"Special Characters:{special_char_count}")

""" 2. get inout from user as a string  and remove duplicates chars from the string

"""

user_string = input("Enter a string: ")
seen= set() # remove duplicates
res=""
for i in user_string:
  if i in seen:
    continue # skip steps and remove for next iteration
  seen.add(i) # add chars in set wont allow duplicates
  res+=i
print(res)

"""3. get input from user reverse it , no slicing use for loop ,find palindrome or not"""

a=input("enter the input: ")
rev=""
for char in a:
  rev=char+rev
print(f"Original string: {a}")
print(f"Reversed string: {rev}")
if a==rev:
  print("It's a palindrome!")
else:
  print("It's not a palindrome.")

"""4. write a code to find it is a anagram or not

"""

str1 = input("Enter first string: ")
str2 = input("Enter second string: ")
if len(str1) != len(str2):
    print("Not anagram")
else:
    count = {}
    for ch in str1:
        count[ch] = count.get(ch, 0) + 1
    for ch in str2:
        count[ch] = count.get(ch, 0) - 1
    if all(value == 0 for value in count.values()):
        print("Anagram")
    else:
        print("Not anagram")

"""5. Fibonacci series

"""

def fibonacci(n):
  if n<=1:
    return n
  return fibonacci(n-1)+fibonacci(n-2)
for i in range(10):
  print(fibonacci(i),end=" ")

# howe work
fing the max occ char in a
string use dic
2. sum of digit using recc
3. compress the string aaabbc -> a3b2c1