# -*- coding: utf-8 -*-
"""Batch b Day 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PLt9K0vF-I5D7iU08ZhC3HfaR3R9JdDJ

#Day5
"""

# find sum of elements in array
# without using built in functions
#find sum from index 2 to 5
arr=[2,5,4,6,7,9]
sum = 0
for i in arr:
    sum += i
print(f"The sum of the elements in the array is: {sum}")
sum=0
for i in range(2,6):
  sum+=arr[i]
print(sum)

# prefix sum
arr = [2, 4, 6, 8, 10]
def build_prefix(arr):
    prefix = []
    total = 0
    for num in arr:
        total += num
        prefix.append(total)
    return prefix
print(build_prefix(arr))

# Find sum from index start to end
def range_sum(prefix, start, end):
    if start == 0:
        return prefix[end]
    return prefix[end] - prefix[start - 1]
arr = [2, 5, 4, 6, 7, 9, 7, 6]
prefix = build_prefix(arr)
print(prefix)
print(range_sum(prefix, 2, 6))

# Clear overwritten Python built-ins
try:
    del range
except:
    pass

try:
    del sum
except:
    pass

try:
    del list
except:
    pass

try:
    del str
except:
    pass

try:
    del int
except:
    pass

print("Cleaned!")

arr = [-7, 1, 5, 2, -4, 3, 0]
def equilibrium(arr):
    total = sum(arr)
    left = 0
    for i in range(len(arr)):
        right= total - left- arr[i]
        if left == right:
            return i
        left =left + arr[i]
    return -1
print(equilibrium(arr))

# sub array equal to total k
arr = [1, 2, 3, 4, 5]
k = 5
for i in range(len(arr)):
    total = 0
    for j in range(i, len(arr)):
        total =total +  arr[j]
        if total == k:
            print(arr[i:j+1])

