# -*- coding: utf-8 -*-
"""Batch B Day 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196QnaaSrLY08aDXZCSi6ql0hLDE3YMbH
"""

arr = [3, 4, 2, 1]
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left = arr[:mid]
        right = arr[mid:]
        merge_sort(left)
        merge_sort(right)
        lp = 0
        rp = 0
        fp = 0
        # Compare left and right
        while lp < len(left) and rp < len(right):
            if left[lp] <= right[rp]:
                arr[fp] = left[lp]
                lp += 1
            else:
                arr[fp] = right[rp]
                rp += 1
            fp += 1
        # Remaining elements in left
        while lp < len(left):
            arr[fp] = left[lp]
            fp += 1
            lp += 1
        # Remaining elements in right
        while rp < len(right):
            arr[fp] = right[rp]
            fp += 1
            rp += 1
merge_sort(arr)
print(arr)

import random
x=random.random()
print(x)

import random
x=random.randint(1,100)
print(x)

import random
x = random.choice(["rock", "paper", "scissors"])
print(x)

import random
arr = [4, 2, 5, 7, 6, 1, 8]
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = random.choice(arr)
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)
print(quick_sort(arr))

