# -*- coding: utf-8 -*-
"""Batch B Day 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kATq_aBWvgK77dZHCNgeO7Vk4LEKC1v0
"""

#linear search
a=[10,20,30,40,50,4,54]
#FIND 50
for i in range(len(a)):
  if a[i]==50:
    print("50 found at index:", i)

#Binary Search
arr = [4, 10, 20, 30, 40, 50, 54]
low = 0
high = len(arr) - 1
while low <= high:
    mid = (low + high) // 2
    if arr[mid] == 50:
        print("50 found at index:", mid)
        break
    elif arr[mid] < 50:
        low = mid + 1
    else:
        high = mid - 1

# first occurance
arr = [1, 2, 4, 4, 4, 6, 7]
target = int(input("Enter target: "))
low = 0
high = len(arr) - 1
while low <= high:
    mid = (low + high) // 2
    if arr[mid] == target:
        first = mid
        high = mid - 1
    elif arr[mid] < target:
        low = mid + 1
    else:
        high = mid - 1
print(target, "found at first index:", first)

# last occurance
arr = [1, 2, 4, 4, 4, 6, 7]
target = int(input("Enter target: "))
low = 0
high = len(arr) - 1
while low <= high:
    mid = (low + high) // 2
    if arr[mid] == target:
        last = mid
        low = mid + 1
    elif arr[mid] < target:
        low = mid + 1
    else:
        high = mid - 1
print(target, "found at last index:", last)

#find square root of anything using binary sarch
n = 50
left = 0
right = n
ans = 0
while left <= right:
    mid = (left + right) // 2
    if mid * mid <= n:
        ans = mid
        left = mid + 1
    else:
        right = mid - 1
print(ans)

arr=[2,5,1,9,3,4,6,8,7]
# sort the array
#dont uase inbuilt function
for i in range(len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]>arr[j]:
            arr[i],arr[j]=arr[j],arr[i]
print(arr)

arr = [64, 25, 12, 22, 11]
n = len(arr)
for i in range(n):
    min_index = i
    for j in range(i + 1, n):
        if arr[j] < arr[min_index]:
            min_index = j
    arr[i], arr[min_index] = arr[min_index], arr[i]
print(arr)