# -*- coding: utf-8 -*-
"""Batch2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovSG86o5Ct66-h-zfztajW13vZ0mlNkW
"""

1/0

try:
  print(1/0)
except:
  print("Zero Division Error")

try:
  x=int(input())
  print(x)
except ValueError as e:
  print(e)
except:
  print("Error")

"""1.# Zero Division Error
2.# valueError
3.# TypeError
4.# indexoutofrange
5.# classnotfound
6.# moduleError
7.# keyError
"""

try:
  x=int(input())
  print(x)
except:
  print("Error")
finally:
  print("Done")

for i in range(5):
  print(i)
  if i==3:
    break
else:
  print("Done")

try:
  x=int(input())
  print(x)
except:
  print("Error")
else:
  print("X is a number")

with open ("file.txt","w") as f:
  f.write("Hello World i am iron man ")

with open ("file.txt","r") as f:
  print(f.read())

x=int(input())
if x<0:
  raise  ValueError("number should be positive")

with open("file.txt","a") as f:
  f.write("\nWith great power comes great responsibility.")

with open ("file.txt","r") as f:
  print(f.read())

class dummy():
  def __init__(self,name,age,city):
    self.name=name
    self.age=age
    self.city=city
  def get_name(self):
    return self.name
  def get_age(self):
    return self.age
  def get_city(self):
    return self.city
  def set_name(self,name):
    self.name=name
  def set_age(self,age):
    self.age=age
  def set_city(self,city):
    self.city=city
  #def __str__(self):
    return f"Name: {self.name}\nAge: {self.age}\nCity: {self.city}"
d=dummy("Spider Man",24,"Los Angels")
print(d.name)
print(d.age)
print(d.city)
print(d.get_age())

while True:
  print("With great power comes great responsibility.")

class Animal():
  def __init__(self, name):
    self.name = name

  def dummy(self):
    print(f"{self.name} is an Animal")

  def sound(self):
    print(f"{self.name} makes an Animal Sound")

  def __str__(self):
    return f"Animal: {self.name}"

class Dog(Animal):
  def __init__(self, name):
    super().__init__(name)

  def dummy(self):
    print(f"{self.name} is a Dog")

  def sound(self):
    print(f"{self.name} barks!")

  def __str__(self):
    return f"Dog: {self.name}"

class Cat(Animal):
  def __init__(self, name):
    super().__init__(name)

  def dummy(self):
    print(f"{self.name} is a Cat")

  def sound(self):
    print(f"{self.name} meows!")

  def __str__(self):
    return f"Cat: {self.name}"

# Demonstration
animal = Animal("Generic Animal")
dog = Dog("Buddy")
cat = Cat("Whiskers")

print(animal)
animal.dummy()
animal.sound()
print("\n")

print(dog)
dog.dummy()
dog.sound()
print("\n")

print(cat)
cat.dummy()
cat.sound()

from abc import abstractmethod,ABC
class BankAccount(ABC):
  def __init__(self,name,balance):
    self.name=name
    self.balance=balance
  def deposit(self,amount):
    self.balance+=amount
  def withdraw(self,amount):
    self.balance-=amount
  def get_balance(self):
    return self.balance
  @abstractmethod
  def interestcal(self):
    pass

class SavingsAcc(BankAccount):
  def interestcal(self):
    return 0.03*self.__balance
S=SavingAcc(100)